    gmSEQ.CHN(numel(gmSEQ.CHN)).NRise=20;
    gmSEQ.CHN(numel(gmSEQ.CHN)).T=[Wait_p+gmSEQ.readout+AfterLaser-20, ...
        Wait_p+gmSEQ.readout+AfterLaser+gmSEQ.halfpi+gmSEQ.m/16+(0:7)*(gmSEQ.pi+gmSEQ.m/8) -20, ...
        Wait_p+gmSEQ.readout+AfterLaser+gmSEQ.halfpi+(gmSEQ.m + 8*gmSEQ.halfpi)-20, ...
        Sig_D_start+gmSEQ.readout+AfterLaser-20, ... 
        Sig_D_start+gmSEQ.readout+AfterLaser+gmSEQ.halfpi+gmSEQ.m/16+(0:7)*(gmSEQ.pi+gmSEQ.m/8) -20, ...
        Sig_D_start+gmSEQ.readout+AfterLaser+gmSEQ.halfpi+(gmSEQ.m + 8*gmSEQ.halfpi)-20];
    gmSEQ.CHN(numel(gmSEQ.CHN)).DT=[gmSEQ.halfpi+40, repelem(gmSEQ.pi+40, 8), gmSEQ.halfpi+40, ... 
        gmSEQ.halfpi+40, repelem(gmSEQ.pi+40, 8), gmSEQ.halfpi+40,];